# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\EG\design_2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(838, 600)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/icon_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 844, 600))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.tab_2.setObjectName("tab_2")
        self.t_floorButton = QtWidgets.QPushButton(self.tab_2)
        self.t_floorButton.setGeometry(QtCore.QRect(20, 130, 130, 40))
        self.t_floorButton.setObjectName("t_floorButton")
        self.zagot_Button = QtWidgets.QPushButton(self.tab_2)
        self.zagot_Button.setGeometry(QtCore.QRect(20, 190, 130, 40))
        self.zagot_Button.setObjectName("zagot_Button")
        self.ccs_Button = QtWidgets.QPushButton(self.tab_2)
        self.ccs_Button.setGeometry(QtCore.QRect(20, 310, 130, 40))
        self.ccs_Button.setObjectName("ccs_Button")
        self.treeWidget = QtWidgets.QTreeWidget(self.tab_2)
        self.treeWidget.setGeometry(QtCore.QRect(180, 10, 271, 561))
        self.treeWidget.setAutoFillBackground(False)
        self.treeWidget.setUniformRowHeights(False)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setAllColumnsShowFocus(False)
        self.treeWidget.setWordWrap(True)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setExpandsOnDoubleClick(False)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.listWidget = QtWidgets.QListWidget(self.tab_2)
        self.listWidget.setGeometry(QtCore.QRect(470, 10, 271, 561))
        self.listWidget.setObjectName("listWidget")
        self.factory2Button = QtWidgets.QPushButton(self.tab_2)
        self.factory2Button.setGeometry(QtCore.QRect(20, 10, 130, 40))
        self.factory2Button.setObjectName("factory2Button")
        self.factory5Button = QtWidgets.QPushButton(self.tab_2)
        self.factory5Button.setGeometry(QtCore.QRect(20, 70, 130, 40))
        self.factory5Button.setObjectName("factory5Button")
        self.btnBrowse = QtWidgets.QPushButton(self.tab_2)
        self.btnBrowse.setGeometry(QtCore.QRect(20, 530, 130, 40))
        self.btnBrowse.setObjectName("btnBrowse")
        self.instr_Button = QtWidgets.QPushButton(self.tab_2)
        self.instr_Button.setGeometry(QtCore.QRect(20, 250, 130, 40))
        self.instr_Button.setObjectName("instr_Button")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EG Схеми"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Схема"))
        self.t_floorButton.setText(_translate("MainWindow", "Тех. поверх"))
        self.zagot_Button.setText(_translate("MainWindow", "Заготівельний цех"))
        self.ccs_Button.setText(_translate("MainWindow", "ЦХШ"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "1"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Фабрика-2"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "2_Р1"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "2_ЩРподрук_Р1"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "2_РП_ЩСУ60"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "2_РП1_ТП59"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "2_РП2_ЩСУП3А1"))
        self.treeWidget.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "2_РП3_ЩСУ60"))
        self.treeWidget.topLevelItem(0).child(4).child(0).setText(0, _translate("MainWindow", "2_ЩР6_РП3"))
        self.treeWidget.topLevelItem(0).child(4).child(0).child(0).setText(0, _translate("MainWindow", "2_ЩО_ЩР6"))
        self.treeWidget.topLevelItem(0).child(5).setText(0, _translate("MainWindow", "2_РП4"))
        self.treeWidget.topLevelItem(0).child(6).setText(0, _translate("MainWindow", "2_РП6"))
        self.treeWidget.topLevelItem(0).child(7).setText(0, _translate("MainWindow", "2_РП7"))
        self.treeWidget.topLevelItem(0).child(7).child(0).setText(0, _translate("MainWindow", "2_ЩОРобомак_РП7"))
        self.treeWidget.topLevelItem(0).child(7).child(1).setText(0, _translate("MainWindow", "2_ЩР20_РП7"))
        self.treeWidget.topLevelItem(0).child(8).setText(0, _translate("MainWindow", "2_РП8_ТП59"))
        self.treeWidget.topLevelItem(0).child(9).setText(0, _translate("MainWindow", "2_РП9_ЩСУП2А1"))
        self.treeWidget.topLevelItem(0).child(10).setText(0, _translate("MainWindow", "2_РП10_ЩСУяч4"))
        self.treeWidget.topLevelItem(0).child(10).child(0).setText(0, _translate("MainWindow", "2_РП10А_РП10"))
        self.treeWidget.topLevelItem(0).child(11).setText(0, _translate("MainWindow", "2_РП11_ТП59"))
        self.treeWidget.topLevelItem(0).child(12).setText(0, _translate("MainWindow", "2_РП12"))
        self.treeWidget.topLevelItem(0).child(13).setText(0, _translate("MainWindow", "2_РП13_ТП59"))
        self.treeWidget.topLevelItem(0).child(13).child(0).setText(0, _translate("MainWindow", "2_ЩР13_РП13"))
        self.treeWidget.topLevelItem(0).child(14).setText(0, _translate("MainWindow", "2_РП17_ТП60П2"))
        self.treeWidget.topLevelItem(0).child(15).setText(0, _translate("MainWindow", "2_РП18"))
        self.treeWidget.topLevelItem(0).child(16).setText(0, _translate("MainWindow", "2_РП28"))
        self.treeWidget.topLevelItem(0).child(17).setText(0, _translate("MainWindow", "2_ЩР1"))
        self.treeWidget.topLevelItem(0).child(18).setText(0, _translate("MainWindow", "2_ЩР2"))
        self.treeWidget.topLevelItem(0).child(19).setText(0, _translate("MainWindow", "2_ЩР3"))
        self.treeWidget.topLevelItem(0).child(20).setText(0, _translate("MainWindow", "2_ЩР3А"))
        self.treeWidget.topLevelItem(0).child(21).setText(0, _translate("MainWindow", "2_ЩР4"))
        self.treeWidget.topLevelItem(0).child(22).setText(0, _translate("MainWindow", "2_ЩР4\'"))
        self.treeWidget.topLevelItem(0).child(23).setText(0, _translate("MainWindow", "2_ЩР5А_РП5А5"))
        self.treeWidget.topLevelItem(0).child(24).setText(0, _translate("MainWindow", "2_ЩП5"))
        self.treeWidget.topLevelItem(0).child(25).setText(0, _translate("MainWindow", "2_ЩР7"))
        self.treeWidget.topLevelItem(0).child(26).setText(0, _translate("MainWindow", "2_ЩР9"))
        self.treeWidget.topLevelItem(0).child(27).setText(0, _translate("MainWindow", "2_ЩОРобомак_ТП60_РП27"))
        self.treeWidget.topLevelItem(0).child(28).setText(0, _translate("MainWindow", "2_ЩС_очисної_уст"))
        self.treeWidget.topLevelItem(0).child(29).setText(0, _translate("MainWindow", "2_ЩСзвардільн_ЩСУ60"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "Фабрика-5"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "5_ЩО1"))
        self.treeWidget.topLevelItem(1).child(0).child(0).setText(0, _translate("MainWindow", "5_ЩО1А_ЩО1"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "5_ЩО2_ТП59_МРП-2А7"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "5_ЩР2_100400"))
        self.treeWidget.topLevelItem(1).child(3).setText(0, _translate("MainWindow", "5_ЩР3"))
        self.treeWidget.topLevelItem(1).child(4).setText(0, _translate("MainWindow", "5_ЩР_4"))
        self.treeWidget.topLevelItem(1).child(5).setText(0, _translate("MainWindow", "5_ЩР_4А"))
        self.treeWidget.topLevelItem(1).child(6).setText(0, _translate("MainWindow", "5_ЩР5"))
        self.treeWidget.topLevelItem(1).child(6).child(0).setText(0, _translate("MainWindow", "5_ЩР5А_ЩР5"))
        self.treeWidget.topLevelItem(1).child(6).child(1).setText(0, _translate("MainWindow", "5_ЩР_робота"))
        self.treeWidget.topLevelItem(1).child(7).setText(0, _translate("MainWindow", "5_ЩР5А\'"))
        self.treeWidget.topLevelItem(1).child(8).setText(0, _translate("MainWindow", "5_ЩР6"))
        self.treeWidget.topLevelItem(1).child(8).child(0).setText(0, _translate("MainWindow", "5_ЩР6А_ЩР6"))
        self.treeWidget.topLevelItem(1).child(8).child(1).setText(0, _translate("MainWindow", "5_ЩР6Б_ЩР6"))
        self.treeWidget.topLevelItem(1).child(8).child(2).setText(0, _translate("MainWindow", "5_ЩР6В_ЩР6"))
        self.treeWidget.topLevelItem(1).child(8).child(3).setText(0, _translate("MainWindow", "5_ЩУ_вент_ЩР6"))
        self.treeWidget.topLevelItem(1).child(8).child(3).child(0).setText(0, _translate("MainWindow", "5_ЩО_сушарки_ЩУ_вент"))
        self.treeWidget.topLevelItem(1).child(9).setText(0, _translate("MainWindow", "5_ЩР14"))
        self.treeWidget.topLevelItem(1).child(10).setText(0, _translate("MainWindow", "5_ЩР160400"))
        self.treeWidget.topLevelItem(1).child(11).setText(0, _translate("MainWindow", "5_ЩР_газ_клапан"))
        self.treeWidget.topLevelItem(1).child(12).setText(0, _translate("MainWindow", "5_ЩС_основа_сушилок"))
        self.treeWidget.topLevelItem(1).child(13).setText(0, _translate("MainWindow", "5_ЩУ1"))
        self.treeWidget.topLevelItem(1).child(14).setText(0, _translate("MainWindow", "ЩР6Б\'"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "ТехПоверх"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "тп_ПР30_А5РП28_ТП60"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "тп_ПР31_ЩСУ60"))
        self.treeWidget.topLevelItem(2).child(2).setText(0, _translate("MainWindow", "тп_ПР32"))
        self.treeWidget.topLevelItem(2).child(3).setText(0, _translate("MainWindow", "тп_ЩО51_РП26_ТП59"))
        self.treeWidget.topLevelItem(2).child(4).setText(0, _translate("MainWindow", "тп_ЩО52_РП25"))
        self.treeWidget.topLevelItem(2).child(4).child(0).setText(0, _translate("MainWindow", "тп_ЩО53_ЩО52"))
        self.treeWidget.topLevelItem(2).child(5).setText(0, _translate("MainWindow", "тп_ЩО54_РП26_ТП59"))
        self.treeWidget.topLevelItem(2).child(5).child(0).setText(0, _translate("MainWindow", "тп_ЩО55_ЩО54"))
        self.treeWidget.topLevelItem(2).child(6).setText(0, _translate("MainWindow", "тп_ЩО56_РП28_ТП60"))
        self.treeWidget.topLevelItem(2).child(6).child(0).setText(0, _translate("MainWindow", "тп_ЩО57_ЩО56"))
        self.treeWidget.topLevelItem(2).child(7).setText(0, _translate("MainWindow", "тп_ЩО59_РП27_ТП60"))
        self.treeWidget.topLevelItem(2).child(7).child(0).setText(0, _translate("MainWindow", "тп_ЩО58_ЩО59"))
        self.treeWidget.topLevelItem(2).child(8).setText(0, _translate("MainWindow", "тп_ЩО6162"))
        self.treeWidget.topLevelItem(2).child(8).child(0).setText(0, _translate("MainWindow", "тп_ЩО62-1"))
        self.treeWidget.topLevelItem(2).child(8).child(1).setText(0, _translate("MainWindow", "тп_ЩО62"))
        self.treeWidget.topLevelItem(2).child(9).setText(0, _translate("MainWindow", "тп_ЩО63\'"))
        self.treeWidget.topLevelItem(2).child(10).setText(0, _translate("MainWindow", "тп_ЩР_кондиціонерів"))
        self.treeWidget.topLevelItem(2).child(11).setText(0, _translate("MainWindow", "тп_ЩС_начОхорони"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "Заготівельний цех"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "зц_РП1А"))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "зц_РП2"))
        self.treeWidget.topLevelItem(3).child(2).setText(0, _translate("MainWindow", "зц_РП6"))
        self.treeWidget.topLevelItem(3).child(2).child(0).setText(0, _translate("MainWindow", "зц_РП8_РП6"))
        self.treeWidget.topLevelItem(3).child(2).child(1).setText(0, _translate("MainWindow", "зц_ЩО_РП6А1"))
        self.treeWidget.topLevelItem(3).child(3).setText(0, _translate("MainWindow", "зц_РП9_ТП43"))
        self.treeWidget.topLevelItem(3).child(4).setText(0, _translate("MainWindow", "зц_РП10"))
        self.treeWidget.topLevelItem(3).child(4).child(0).setText(0, _translate("MainWindow", "зц_ЩОрозкрой_РП10А4"))
        self.treeWidget.topLevelItem(3).child(5).setText(0, _translate("MainWindow", "зц_РП11"))
        self.treeWidget.topLevelItem(3).child(6).setText(0, _translate("MainWindow", "зц_РП12"))
        self.treeWidget.topLevelItem(3).child(7).setText(0, _translate("MainWindow", "зц_РП15"))
        self.treeWidget.topLevelItem(3).child(8).setText(0, _translate("MainWindow", "зц_ШП1"))
        self.treeWidget.topLevelItem(3).child(9).setText(0, _translate("MainWindow", "зц_ЩО3"))
        self.treeWidget.topLevelItem(3).child(10).setText(0, _translate("MainWindow", "зц_ЩО3А"))
        self.treeWidget.topLevelItem(3).child(11).setText(0, _translate("MainWindow", "зц_ЩО7"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "Інструментальний"))
        self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "ін_РП29_ТП43"))
        self.treeWidget.topLevelItem(4).child(1).setText(0, _translate("MainWindow", "ін_РП30_ТП43"))
        self.treeWidget.topLevelItem(4).child(1).child(0).setText(0, _translate("MainWindow", "ін_РП38_РП30"))
        self.treeWidget.topLevelItem(4).child(1).child(1).setText(0, _translate("MainWindow", "ін_РП39_РП30"))
        self.treeWidget.topLevelItem(4).child(1).child(2).setText(0, _translate("MainWindow", "ін_ЩО40_РП30"))
        self.treeWidget.topLevelItem(4).child(2).setText(0, _translate("MainWindow", "ін_РП33_ТП43"))
        self.treeWidget.topLevelItem(4).child(2).child(0).setText(0, _translate("MainWindow", "ін_ЩО33_РП33"))
        self.treeWidget.topLevelItem(4).child(3).setText(0, _translate("MainWindow", "ін_РП40_ТП43"))
        self.treeWidget.topLevelItem(4).child(4).setText(0, _translate("MainWindow", "ін_РП41_ТП43"))
        self.treeWidget.topLevelItem(4).child(4).child(0).setText(0, _translate("MainWindow", "ін_РП32_РП41"))
        self.treeWidget.topLevelItem(4).child(4).child(0).child(0).setText(0, _translate("MainWindow", "ін_ЩС32_РП32"))
        self.treeWidget.topLevelItem(4).child(5).setText(0, _translate("MainWindow", "ін_ЩО39"))
        self.treeWidget.topLevelItem(4).child(6).setText(0, _translate("MainWindow", "ін_ЩС_ерозійна"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("MainWindow", "ЦХШ"))
        self.treeWidget.topLevelItem(5).child(0).setText(0, _translate("MainWindow", "ц_РП16_ТП43"))
        self.treeWidget.topLevelItem(5).child(1).setText(0, _translate("MainWindow", "ц_РП17_ТП43"))
        self.treeWidget.topLevelItem(5).child(2).setText(0, _translate("MainWindow", "ц_РП18_ТП43"))
        self.treeWidget.topLevelItem(5).child(3).setText(0, _translate("MainWindow", "ц_ЩО1_ТП43"))
        self.treeWidget.topLevelItem(5).child(4).setText(0, _translate("MainWindow", "ц_ЩО2ЦХШ_ТП43"))
        self.treeWidget.topLevelItem(5).child(5).setText(0, _translate("MainWindow", "ц_ЩРслюсЦХШ_ТП43"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.factory2Button.setText(_translate("MainWindow", "Фабрика-2"))
        self.factory5Button.setText(_translate("MainWindow", "Фабрика-5"))
        self.btnBrowse.setText(_translate("MainWindow", "Пошук"))
        self.instr_Button.setText(_translate("MainWindow", "Інструментальний"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Список"))
import qt_rc
